server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.154.130:1521:helowin
    username: zyg1
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: 192.168.154.130
    database: 0
    port: 6379
    password:
    timeout: 300ms
    lettuce:
      pool:
        max-wait: -1
        max-active: 8

redis:
  database: test
  key:
    authCode: "user:authCode"
    userInfo: "user:userInfo"
  expire:
    authCode: 60
    userInfo: 86400

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml #类路径下mapper目录中的所有xml文件

logging:
  level:
    root: debug
